name: Build and Deploy to GCP

on:
  push:
    branches: [ deploy-prod, deploy-staging, deploy-dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Setup cloud sdk
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to GCS
        run: |
          BUCKET_NAME="baaahsorg-$(echo ${BRANCH_NAME} | cut -d'-' -f 2)"
          gsutil -m rsync -r -d ./build gs://${BUCKET_NAME}
        env:
          BRANCH_NAME: ${{ github.ref }}
        shell: bash